### ISSUE TITLE
help julia buntaine submit a podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#11]
josephine
can you assign this to someone- i didnt mean you to do all of these but as you are the overall coordinator i thought it best to have you assign them

corey- there are now about 5 people willing to send in podcasts themselves-but we
need to get them clear instuctions how to submit podcasts-this will help you build up the back log
@coreysmart92 

roger

Hi Roger,

I would love to add a podcast to Creative Disturbance. I've been following this project and think it's fantastic. Send along instructions!

Take care.

Julia Buntaine
info@sciartcenter.org

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#130
