### ISSUE TITLE
help marti hearst submit a podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#12]
josephine
can you assign this to someone to help this person submit a podcast for the
new leonardo channel-they need clear instructions on how to submit a podcast

roger

if you can get these podcasts submitted it will help you build up hte back log

roger

@coreysmart92 

Marti A HEARST via alum.mit.edu 
7:54 PM (14 hours ago)

to roger 
I could be interested, but do not want to take the time to edit the
recording you have of me.

marti hearst
hearst@berkeley.edu

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#129
