### ISSUE TITLE
help jill scot submit podcasts for new leonardos

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#14]
send jill scot instructions on how to submit podcasts

roger

Hay Roger,

Great to hear from you! I hope all is well...

As we are planing to start up LASER talks here next year in Zurich- 
please send me the instructions for the Podcasts.

Cheers and look forward to seeing you in Vancover,

Jill
Scott Jillian Margaret <jillian.scott@zhdk.ch>

Prof. Dr. Jillian Scott
Art and Science Research
Research Advisor: Artistsinlabs (www.artistsinlabs.ch)
Director of Studies: z-node-Planetary Collegium (z-node.net)
Institute for Cultural Studies in the Arts
University of Applied Science
Toni Areal. Pfingstweiderstr, 96
8005 Zurich, Switzerland
Phone: +41(0)795249211
Private web site: www.jillscott.org

**Comment by porteriffic** [comment]
Emailed Jill
