### ISSUE TITLE
help ioannis zannos submit a podcast for new leonardos channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#15]
send
Ioannis Zannos instructions on how to submit a podcast

zannos@gmail.com

for new leonardos channel

roger

3:57 PM (21 hours ago)

to roger, Sheila, Yiannis, Tleeser, lawrence.harvey, Soraya, Ionat 
Dear Roger, 

thank you for the invitation.  Will consider preparing a podcast with colleagues here or even better involving partners in international cooperations. 

Iannis Zannos

**Comment by rmalina** [comment]
josephine-no hurry-assig  to someone else ok
roger

**Comment by porteriffic** [comment]
Emailed Iannis

**Comment by rmalina** [comment]
josephine
thanks for sending the instructions to the people who will be depositing podcasts=
i see you have closed those actions-maybe worth at least contact all of them in a month
if they havent submitted podcasts
we need to be proactive to build up a backlog !
roger
@cassininazir
