### ISSUE TITLE
help katharine hawthorne submit a podcast ffor new leonardos

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#16]
can you assign to somomeone

helpKatharine Hawthorne <kmhawthorne@gmail.com>
submit a pre recorded postcast

roger
10:51 PM (18 hours ago)

to roger 
Hi Roger,
We presented at the same LASER at Stanford in March, and I was happy to receive your email.  I am interested in publishing a podcast and would love to receive further instructions.
All best,
Katharine

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#127
