### ISSUE TITLE
help marcy darnovsky submit a pocast for new leonardos channel

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#17]
can you assign to someione to follow up to help
Marcy Darnovsky darnovsky@geneticsandsociety.org via alum.mit.edu 
6:53 PM (22 hours ago)

to roger 
Dear Roger,

Thanks for your email. The podcast compilation is a great idea. Would it be appropriate to suggest you open to posting radio programs on which I was interviewed? 

Best
Marcy

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#126
