### ISSUE TITLE
help lilla submit a podcast for new leonardos

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#19]
please send instructions on how to sumit a podcast to

Lilla LoCurto <loc.out@verizon.net>

**Comment by porteriffic** [comment]
@coreysmart92 I made some minor changes to the [Podcast Production Cheat Sheet](https://docs.google.com/document/d/1Io4Cj1Btt56jifbt4I8R1K4fdX1JYHPEzaYHbLAQBKY/edit). Please download this document as a PDF to send to Lilla and others you are assigned to. Call, email, or text if you need help compiling an email.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#124
