### ISSUE TITLE
Do Podcast with Alejandro Jacobo - UTD Startup

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#2]
http://www.rolloutaec.com/
alejandro jacobo has a utd startup
and is available for a podcast

maybe judd bradbury could do it
@yvantina @coreysmart92 

anyone else interested in recording it this summer 

roger
Roger
je viens de rencontrer ce gars a la gym
il vient de lancer sa startup ici a utd avec un ami a lui (business major et computer science)

http://www.rolloutaec.com/

le projet a l'air intéressant et ils veulent faire un podcast cet été
l'ouverture officielle de leur startup a lieu dans deux semaines donc je dirais après polyglot week
seulement je ne sais pas qui pourrait être leur interlocuteur parce que j'ai déjà beaucoup de choses à faire
mais je pense que ca pourrait contribuer à développer le côté 'technology entrepreneurship' de CD

pas d'urgence - juste pour info

je travaille sur le doc AVVA ce week-end et je skype avec Yannick mardi prochain

yvan

---------- Forwarded message ----------
From: Alejandro Jacobo <ajacobo@rolloutaec.com>
Date: 2015-06-06 14:57 GMT-05:00
Subject: Rollout
To: "yvantina@gmail.com" <yvantina@gmail.com>

Rolloutaec.com

Alejandro Jacobo
Sent from iPhone
979-676-1663

**Comment by yvantina** [comment]
Yes
Podcast record is scheduled for next week, Thursday June 25, 11am - 1 pm in
the artscilab so please make sure we have all equipment ready

**Comment by yvantina** [comment]
Done ! Issue closed
