### ISSUE TITLE
Record Podcast with Nigerians

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#3]
for yvan tina
@porteriffic 

Dear R. O. ROM KALILU, T. E. AKINDE and G. N. OGWU

This is roger malina, executive editor of the leonardo publications

thank you for submitting your text

FRUIT PEELINGS AS ASH GLAZES:
WASTE PHENOLOGY AND ARTISTIC PRAXIS

the topic is a bit outside our normal editorial scope but as a technical
article it brings an interesting topic

I am approving this to be sent out for peer review-given the specialised
nature of the topic our coordinating editor nic cronbach may ask you
for suggestions of peer reviewers

while the article is in our peer review process i would like to see
if you might be interested in recording over the phone or skype
a 15 minute audio podcast to be published on our leonardo Creative
Disturbance Virtual Africa channel (independent of whether the peer
reviewers approve publication)

http://creativedisturbance.org/channel/virtual-africa/

we are working hard to make the work of art and technology experts
in africa visible to the worldwide audience and you might be interested
in this opportunity

i introduce you to the producer of this channel, yvan tina who will
discuss this with you if you are interested ( M Tina is originally
from cameroons)

Thank you for your interest in using leonardo journal to document your work

**Comment by yvantina** [comment]
@rmalina Have sent an email to both  Kalilu et.al AND Morgan Trevor 3 weeks ago. Have not received any reply yet.

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#136
