### ISSUE TITLE
Set Up Podcast with Elena Cologni

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#4]
o Josephine, Elena 
elena
assume this is to do a creative disturbance podcast
would be delighted to set one up
what would you like to talk about !

roger malina

**Comment by rmalina** [comment]
elena cologhni is at  
Elena Cologni <ecologni@gmail.com> 
web site
http://www.elenacologni.com/index2.htm
can you assign this to one of the production team ?
i can be in the podcast with her

**Comment by rmalina** [comment]
Hi Roger
I think the topic would be 'disruptions in processes of memorisation' as it was discussed in   
http://rockfluid.com/cambridge-science-festival-2012 and informed the participatory 
http://rockfluid.com/spaecious  and http://rockfluid.com/bergamo-spaecious which 'creates the physical and  psychological conditions to enhance an  awareness of the perception – and illusion – of time and space in the present' 

Disruptions in this case enhance the social dynamics among the participants 
Best Elena

**Comment by porteriffic** [comment]
@amb141330 Would you be willing to set this up after you return from vacay?

**Comment by halclark** [comment]
This issue was moved to creativedisturbance/podcasts#135
