### ISSUE TITLE
help julie newdoll submit a podcast

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/intellectual-dating#9]
please can you email julie
Julie Newdoll <julie@brushwithscience.com>

who wants to submit a podcast and needs further help

roger

11:47 AM (1 minute ago)

julie
I
attach instructions- they seem rather complicated to me
basically you can send us a sound file MP3 or whatver with
the podcast in it ( the instructions are for channel producers
i will get a modified version for submitted podcasts)

we prefer podcasts under 15 minutes because people listening ( eg when
commuting) are likely not to be able to listen to long podcasts

in general we recommend dialogues rather than monologues-people
pay more attention to dialogues

if you have any other questions contact me or
josephine porter Josephine Porter <porteriffic@gmail.com>
the project coordinator

roger

Podcast Production Cheat Sheet

Introduction

Thank you for your interest in creating a podcast with us here at
Creative Disturbance! This document serves as a quick reference on
what we call the “production” of your podcast. You should find tips to
help you as you produce your podcast from A to Z.

Table of Contents

Pre-Production

Timing

Environment

Equipment

Preparation

     2.  Recording a Podcast

Recording Setup

The Conversation

     3.  Post-Production

Post-Recording

Uploading a Podcast

Pre-Production

Timing

Allow yourself at least an hour for the setup and recording of the
podcast. You won’t be recording the full hour, but this gives you and
your guest time to prepare equipment.

The podcast should be 10-15 minutes long (the free version of Pamela
cuts off exactly at 15 minutes)

Environment

If possible, choose a location that has:

None or very little background noise

No interruptions

Avoid public places such as coffeeshops or locations where other
voices will be overheard.

Sound proofing

Rugs and carpet reduce reverb/echos. Concrete, tile and metals echo
sound and do not provide an ideal recording environment.

A fast internet connection.

This will prevent lags and gaps in your recording. Skype can test your
internet connection through “Check Settings.”

For more information on Skype internet speed support, visit:
https://support.skype.com/en/faq/FA1417/how-much-bandwidth-does-skype-need

Audio recording specifications: Ideal minimum is 30kbps; 100kbps recommend.

Video recording specifications: 128kbps minimum; 300 kpbs recommend.
(Note that we will only use the audio from a video recording).

Equipment

If possible, use a headset with a mic (not mandatory but highly
recommended for audio)

You can choose to record your podcast using a few methods:

You may download Skype recording software appropriate for your operating system:

Ecamm Call Recorder (Mac): ecamm.com/mac/callrecorder

Pamela (PC): pamela.biz/en/download

Free version has maximum of 15 minute recording time)

With Pamela, make sure to hit the Record button and not the Record Video Button

For Ubuntu (Linux) users: atdot.ch/scr

You may use the recording feature of a smartphone

For iPhones, open up the Voice Memo application that comes with the
iPhone as default.

You may use a standard quality microphone (if you already have one).

Zoom mics are fantastic portable mics for a decent price

Preparation

Open Skype application and connect to the guest speaker

After the call is successfully made, open the recording software.

When both programs are open (Skype and your recording software), press
“Start” to record your conversation.

2. Recording a Podcast

Don’t know how to set up your recording session? What are you supposed
to even say at the beginning of your podcast? Keep reading!

Recording Setup

i. After both Skype and the appropriate recording software are open,
perform a sound test by:

Confirming that you can hear each other.

Audio quality is acceptable. Audio quality is a function of internet speed.

Make sure you and your guest(s) are stationary while talking. If you
are constantly moving back and forth in your chair or around the
computer it will affect the audio quality.

Set initial mic volume for both parties. This will prevent voices
being too loud and reduce feedback.

b. The Conversation

Open the podcast with
“ Welcome to Creative Disturbance, this is the [Channel Name]. My name
is [Your Name] and I’m talking with [Guest Name(s)] in [Location(s)]
”.

Discuss the topic(s) with your guest.

End the podcast, with “To learn more about [Guest Speakers Name] visit
the Creative Disturbance site at creativedisturbance.org”

Save the audio recording to your computer. You will upload this file
(possible file formats: .wav or .aiff preferred; .mp4 is acceptable)
later to the Creative Disturbance website.

Reminders:

Create a dialogue, not an interview. Make sure the conversation is not
one sided. Have a discussion together around a topic.

Please, no promotion of products or platforms (perhaps limited
promotion or directed promotion).

If you need to start a segment again, pause a few seconds (silence for
editing) before you begin the discussion again.

At the end of your podcast, ask guest to nominate(for a podcast we can
do with them):

Someone they know, and someone they don't know

Find out if okay to get that individual's content

3. Post-Production

You’re finished recording. Great! What do you do now?

Post-Recording

After you’re done recording:

Listen to the show

Ensure high audio quality and is clear

Pick out keywords for tags

Write a description for the episode

     b.  Uploading a Podcast

You’re done recording your podcast. Great! Now what?

Take a gander at our checklist:

Does your podcast need to be edited by our fantastic audio editors?

Or did you edit your own podcast?

Are you having issues uploading?

If your podcast needs to be edited:

Please place your podcast in the folder titled “Needs Editing” under
your channel folder. So it should go something like this:

Open Creative Disturbance Dropbox >> Open the Channel folder >> Select
your channel >> Open “Needs Editing” >> Drop your podcast into “Needs
Editing” folder

Please expect to receive at least 3 emails during the production of your podcast

The first email will be from one of our audio editors, notifying you
that they’ve begun editing your podcast.

The second email will be a notification that your podcast is done and
ask that you listen to your podcast (for feedback) before the podcast
is published.

The third and final email will be a notification that your podcast has
been published on the Creative Disturbance website.

     2.   If you edited your own podcast (intros and outro included):

Please place your podcast in the folder titled “Completed Podcast”
under your channel folder. So the process should look something like
this:

Open Creative Disturbance Dropbox >> Open the Channel folder >> Select
your channel >> Open “Completed Podcast” >> Drop your podcast into
“Completed Podcast” folder

If you’re dropping your podcast into the “Completed Podcast” folder,
we assume everything has been done on your end and it will be uploaded
as is. If something is missing from your podcast (for example intros
and outros), please place your podcast in the “Needs Editing” folder.

    3.   Contact the Channel Manager at
feedback.createdisturb@gmail.com if you can’t upload.

If the podcast is larger than the upload limit, compress the file
(.zip, .tar, .gz, .sit, etc) and upload. If you still have trouble
uploading, email feedback.createdisturb@gmail.com.

Remember, if your podcast is large, please give it time to upload. It
might take a while.

Thank you for contributing to Creative Disturbance! We hope that this
document has been helpful. Please do not hesitate to contact us at
feedback.createdisturb@gmail if you run across any issues. It has been
a pleasure working with you!

The Creative Disturbance Team

**Comment by porteriffic** [comment]
Emailed Julie.
